<?php

namespace SN\AsymfoniaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * langueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class langueRepository extends EntityRepository
{
}
